# Generated by Django 4.2.2 on 2023-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
